[network]
name = "simnet"

[accounts.deployer]
mnemonic = "ability metal blind spot this era submit twice electric struggle fish adult"
balance = 10000000000000000

[accounts.wallet_1]
mnemonic = "twice robust ramp fiber glue hunt excuse prevent clump toward ethics about"
balance = 10000000000000000
