[project]
name = "gm-on-stacks"
description = "Say GM and mint GM NFTs on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.gm-on-stacks-v7]
path = "contracts/gm-on-stacks-mainnet.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
